services:
  postgres:
    image: postgres:16
    container_name: postgres_virtual
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: comments
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
